### ISSUE TITLE
Judicious Logging

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/mpc-etl-jobs#9]
Currently, https://github.com/Samagra-Development/mpc-etl-jobs/blob/165dff3e76d8721074eb09502516aaf89f969cdc/src/app.py#L122 is filling up the server with logs. 

Removing this and adding just the number of records would be more meaningful.

**Comment by radhay-samagra** [comment]
added decorator to log time for api and removed unwanted logs
